'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { supabase } from '../../../../lib/supabase';

type Answer = 'Yes' | 'No' | '';

type Principle = {
  id: number;
  name: string;
  description: string;
};

type SeparationQuestion = {
  id:
    | 'space'
    | 'time'
    | 'relation'
    | 'system'
    | 'direction'
    | 'simultaneous'
    | 'bypass';

  title: string;
  question: string;
  principleIds: number[];
};

/* =========================================================
   INVENTIVE PRINCIPLES USED IN PHYSICAL CONTRADICTION
   ========================================================= */

const PRINCIPLES: Principle[] = [
  {
    id: 1,
    name: 'Segmentation',
    description:
      'Divide an object into independent parts, make it easy to assemble or disassemble, or increase its degree of segmentation.',
  },
  {
    id: 2,
    name: 'Taking Out',
    description:
      'Separate an interfering part or property from an object, or extract only the necessary part or property.',
  },
  {
    id: 3,
    name: 'Local Quality',
    description:
      'Change an object from uniform to nonuniform and allow different parts to perform under conditions best suited to them.',
  },
  {
    id: 4,
    name: 'Asymmetry',
    description:
      'Change a symmetrical form into an asymmetrical one or increase the degree of existing asymmetry.',
  },
  {
    id: 5,
    name: 'Merging',
    description:
      'Combine identical or similar objects, operations or functions.',
  },
  {
    id: 6,
    name: 'Universality',
    description:
      'Make an object or its parts perform several functions.',
  },
  {
    id: 7,
    name: 'Nested Doll',
    description:
      'Place one object inside another or allow parts to move within spaces of other objects.',
  },
  {
    id: 9,
    name: 'Preliminary Anti-Action',
    description:
      'Perform an opposite or compensating action in advance to reduce an expected harmful effect.',
  },
  {
    id: 10,
    name: 'Preliminary Action',
    description:
      'Perform required changes in advance or arrange objects beforehand so they are ready when needed.',
  },
  {
    id: 11,
    name: 'Beforehand Cushioning',
    description:
      'Prepare emergency or compensating means in advance to counteract undesirable effects.',
  },
  {
    id: 12,
    name: 'Equipotentiality',
    description:
      'Change operating conditions so unnecessary changes of position or energy level can be avoided.',
  },
  {
    id: 13,
    name: 'The Other Way Round',
    description:
      'Perform the opposite action, reverse movable and stationary parts, or turn the object or process around.',
  },
  {
    id: 14,
    name: 'Curvature / Spheroidality',
    description:
      'Replace straight forms with curved ones and use cylinders, spheres, spirals or rotary motion.',
  },
  {
    id: 15,
    name: 'Dynamics',
    description:
      'Allow an object, environment or process to change so that it operates under optimal conditions.',
  },
  {
    id: 17,
    name: 'Another Dimension',
    description:
      'Move into another dimension, use multi-level arrangements, tilt objects or use another side or orientation.',
  },
  {
    id: 19,
    name: 'Periodic Action',
    description:
      'Replace continuous action with periodic or pulsating action, or change an existing action frequency.',
  },
  {
    id: 25,
    name: 'Self-Service',
    description:
      'Make an object service itself or use waste energy, substances or resources generated by the system.',
  },
  {
    id: 28,
    name: 'Mechanics Substitution',
    description:
      'Replace mechanical means with optical, acoustic, electrical, magnetic or electromagnetic interactions.',
  },
  {
    id: 31,
    name: 'Porous Materials',
    description:
      'Make an object porous, add porous elements or use the pores to provide an additional function.',
  },
  {
    id: 32,
    name: 'Color Changes',
    description:
      'Change color, transparency or optical properties to improve observation or operation.',
  },
  {
    id: 33,
    name: 'Homogeneity',
    description:
      'Use interacting objects made from the same material or materials with similar properties.',
  },
  {
    id: 34,
    name: 'Discarding and Recovering',
    description:
      'Discard, dissolve, modify or regenerate parts after they have fulfilled their function.',
  },
  {
    id: 35,
    name: 'Parameter Changes',
    description:
      'Change physical state, concentration, flexibility, temperature, volume or another system parameter.',
  },
  {
    id: 36,
    name: 'Phase Transitions',
    description:
      'Use phenomena associated with phase transitions, such as volume changes or absorption and release of heat.',
  },
  {
    id: 37,
    name: 'Thermal Expansion',
    description:
      'Use thermal expansion or contraction, including materials with different thermal expansion coefficients.',
  },
  {
    id: 38,
    name: 'Strong Oxidants / Catalysts',
    description:
      'Use catalysts or modify the oxidizing environment to strengthen or accelerate the required process.',
  },
  {
    id: 39,
    name: 'Inert Environment',
    description:
      'Replace the normal environment with an inert one, add neutral substances or use a vacuum.',
  },
  {
    id: 40,
    name: 'Composite Materials',
    description:
      'Replace homogeneous materials with composite materials having different complementary properties.',
  },
];

/* =========================================================
   PHYSICAL CONTRADICTION SEPARATION QUESTIONS
   ========================================================= */

const QUESTIONS: SeparationQuestion[] = [
  {
    id: 'space',
    title: 'Separation in Space',
    question:
      'Can the contradictory requirements be satisfied in different places or different parts of the system?',
    principleIds: [1, 2, 3, 7, 4, 17],
  },
  {
    id: 'time',
    title: 'Separation in Time',
    question:
      'Can the contradictory requirements be satisfied at different moments in time?',
    principleIds: [9, 10, 11, 15, 34],
  },
  {
    id: 'relation',
    title: 'Separation by Relation',
    question:
      'Can the required property depend on a specific condition, interaction or relationship?',
    principleIds: [3, 17, 19, 31, 32, 40],
  },
  {
    id: 'system',
    title: 'Separation at System Level',
    question:
      'Can one requirement be satisfied by the system while the opposite requirement is satisfied by its parts or supersystem?',
    principleIds: [1, 5, 12, 33],
  },
  {
    id: 'direction',
    title: 'Separation by Direction',
    question:
      'Can the contradictory properties exist in different directions or orientations?',
    principleIds: [4, 14, 17, 32, 35, 40],
  },
  {
    id: 'simultaneous',
    title: 'Satisfy Both Requirements',
    question:
      'Can both contradictory requirements be satisfied simultaneously by changing the physical principle or system parameter?',
    principleIds: [13, 28, 35, 36, 37, 38, 39],
  },
  {
    id: 'bypass',
    title: 'Bypass the Contradiction',
    question:
      'Can the need for one of the contradictory requirements be eliminated or bypassed entirely?',
    principleIds: [6, 13, 25],
  },
];

export default function PhysicalContradictionPage() {
  const params = useParams();
  const router = useRouter();

  const projectId = params.id as string;

  const [projectName, setProjectName] = useState('');

  const [primaryContradiction, setPrimaryContradiction] =
    useState('');

  const [reverseContradiction, setReverseContradiction] =
    useState('');

  const [state1, setState1] = useState('');
  const [state1Justification, setState1Justification] =
    useState('');

  const [state2, setState2] = useState('');
  const [state2Justification, setState2Justification] =
    useState('');

  const [answers, setAnswers] = useState<
    Record<SeparationQuestion['id'], Answer>
  >({
    space: '',
    time: '',
    relation: '',
    system: '',
    direction: '',
    simultaneous: '',
    bypass: '',
  });

  const [proposedSolution, setProposedSolution] =
    useState('');

  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const [error, setError] = useState('');
  const [message, setMessage] = useState('');

  useEffect(() => {
    loadPage();
  }, [projectId]);

  function dbToAnswer(
    value: boolean | null | undefined
  ): Answer {
    if (value === true) return 'Yes';
    if (value === false) return 'No';

    return '';
  }

  function answerToDb(value: Answer) {
    if (value === 'Yes') return true;
    if (value === 'No') return false;

    return null;
  }

  async function loadPage() {
    setLoading(true);
    setError('');

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      router.push('/login');
      return;
    }

    const { data: project, error: projectError } =
      await supabase
        .from('projects')
        .select('name')
        .eq('id', projectId)
        .single();

    if (projectError || !project) {
      setError('Project could not be found.');
      setLoading(false);
      return;
    }

    setProjectName(project.name);

    const {
      data: technical,
      error: technicalError,
    } = await supabase
      .from('technical_contradictions')
      .select(
        'primary_contradiction, reverse_contradiction'
      )
      .eq('project_id', projectId)
      .maybeSingle();

    if (technicalError) {
      setError(technicalError.message);
      setLoading(false);
      return;
    }

    if (technical) {
      setPrimaryContradiction(
        technical.primary_contradiction || ''
      );

      setReverseContradiction(
        technical.reverse_contradiction || ''
      );
    }

    const {
      data: existing,
      error: physicalError,
    } = await supabase
      .from('physical_contradictions')
      .select('*')
      .eq('project_id', projectId)
      .maybeSingle();

    if (physicalError) {
      setError(physicalError.message);
      setLoading(false);
      return;
    }

    if (existing) {
      setState1(existing.state_1 || '');

      setState1Justification(
        existing.state_1_justification || ''
      );

      setState2(existing.state_2 || '');

      setState2Justification(
        existing.state_2_justification || ''
      );

      setAnswers({
        space: dbToAnswer(
          existing.separate_space
        ),

        time: dbToAnswer(
          existing.separate_time
        ),

        relation: dbToAnswer(
          existing.separate_relation
        ),

        system: dbToAnswer(
          existing.separate_system_level
        ),

        direction: dbToAnswer(
          existing.separate_direction
        ),

        simultaneous: dbToAnswer(
          existing.satisfy_simultaneously
        ),

        bypass: dbToAnswer(
          existing.bypass
        ),
      });

      setProposedSolution(
        existing.proposed_solution || ''
      );
    }

    setLoading(false);
  }

  function setAnswer(
    id: SeparationQuestion['id'],
    answer: Answer
  ) {
    setAnswers((previous) => ({
      ...previous,
      [id]: answer,
    }));

    setMessage('');
    setError('');
  }

  const recommendedPrinciples =
    useMemo(() => {
      const principleIds = new Set<number>();

      QUESTIONS.forEach((question) => {
        if (answers[question.id] === 'Yes') {
          question.principleIds.forEach(
            (id) => principleIds.add(id)
          );
        }
      });

      return Array.from(principleIds)
        .sort((a, b) => a - b)
        .map((id) =>
          PRINCIPLES.find(
            (principle) =>
              principle.id === id
          )
        )
        .filter(
          (
            principle
          ): principle is Principle =>
            principle !== undefined
        );
    }, [answers]);

  const allQuestionsAnswered =
    QUESTIONS.every(
      (question) =>
        answers[question.id] !== ''
    );

  async function savePhysicalContradiction(
    goNext = false
  ) {
    setError('');
    setMessage('');

    if (goNext) {
      if (!state1.trim()) {
        setError(
          'Please describe State 1.'
        );
        return;
      }

      if (!state1Justification.trim()) {
        setError(
          'Please explain why State 1 is required.'
        );
        return;
      }

      if (!state2.trim()) {
        setError(
          'Please describe State 2.'
        );
        return;
      }

      if (!state2Justification.trim()) {
        setError(
          'Please explain why State 2 is required.'
        );
        return;
      }

      if (!allQuestionsAnswered) {
        setError(
          'Please answer all seven separation questions before continuing.'
        );
        return;
      }
    }

    setSaving(true);

    const { error: saveError } =
      await supabase
        .from('physical_contradictions')
        .upsert(
          {
            project_id: projectId,

            state_1: state1.trim(),

            state_1_justification:
              state1Justification.trim(),

            state_2: state2.trim(),

            state_2_justification:
              state2Justification.trim(),

            separate_space:
              answerToDb(answers.space),

            separate_time:
              answerToDb(answers.time),

            separate_relation:
              answerToDb(
                answers.relation
              ),

            separate_system_level:
              answerToDb(answers.system),

            separate_direction:
              answerToDb(
                answers.direction
              ),

            satisfy_simultaneously:
              answerToDb(
                answers.simultaneous
              ),

            bypass:
              answerToDb(answers.bypass),

            proposed_solution:
              proposedSolution.trim(),

            updated_at:
              new Date().toISOString(),
          },
          {
            onConflict: 'project_id',
          }
        );

    if (saveError) {
      setSaving(false);
      setError(saveError.message);
      return;
    }

    if (goNext) {
      const { error: projectError } =
        await supabase
          .from('projects')
          .update({
            current_step:
              'Final Report',
          })
          .eq('id', projectId);

      if (projectError) {
        setSaving(false);
        setError(
          projectError.message
        );
        return;
      }

      router.push(
        `/project/${projectId}/final-report`
      );

      return;
    }

    setSaving(false);

    setMessage(
      'Physical Contradiction saved successfully.'
    );
  }

  if (loading) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-[#f4f2e9] text-[#123d36]">
        <p className="font-semibold">
          Loading Physical Contradiction...
        </p>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-[#f4f2e9] text-[#123d36]">

      <header className="border-b border-[#d8d5ca] bg-white">

        <div className="mx-auto flex max-w-7xl items-center justify-between px-8 py-5">

          <div>

            <p className="text-sm font-bold uppercase tracking-[0.25em] text-[#57b89d]">
              TRIZup
            </p>

            <h1 className="text-xl font-bold">
              TRIZ Innovation Workspace
            </h1>

          </div>

          <button
            onClick={() =>
              router.push('/dashboard')
            }
            className="rounded-lg border border-[#123d36] px-5 py-2.5 text-sm font-semibold hover:bg-[#edf3f1]"
          >
            My Projects
          </button>

        </div>

      </header>

      <section className="mx-auto max-w-7xl px-6 py-12">

        <div className="mb-10">

          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#57b89d]">
            Step 9 of 10
          </p>

          <h2 className="mt-2 text-4xl font-bold">
            Physical Contradiction
          </h2>

          <p className="mt-3 text-[#66736f]">
            {projectName}
          </p>

        </div>

        <div className="mb-8 rounded-2xl bg-[#e8f5f1] p-6">

          <p className="font-semibold">
            Define two opposite states required
            from the same system, object or
            parameter.
          </p>

          <p className="mt-2 max-w-4xl text-sm leading-6 text-[#5e706b]">
            Then determine whether the
            contradictory requirements can be
            separated in space, time, relation,
            system level, direction or by another
            TRIZ separation strategy.
          </p>

        </div>

        {/* TECHNICAL CONTRADICTIONS */}

        <div className="grid gap-6 lg:grid-cols-2">

          <ReadonlyCard
            title="Primary Technical Contradiction"
            value={primaryContradiction}
          />

          <ReadonlyCard
            title="Reverse Technical Contradiction"
            value={reverseContradiction}
          />

        </div>

        {/* STATES */}

        <div className="mt-8 grid gap-6 lg:grid-cols-2">

          <StateCard
            number="1"
            state={state1}
            setState={setState1}
            justification={
              state1Justification
            }
            setJustification={
              setState1Justification
            }
          />

          <StateCard
            number="2"
            state={state2}
            setState={setState2}
            justification={
              state2Justification
            }
            setJustification={
              setState2Justification
            }
          />

        </div>

        {/* QUESTIONS */}

        <div className="mt-8 rounded-3xl bg-white p-7 shadow-sm">

          <div>

            <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#57b89d]">
              Separation Analysis
            </p>

            <h3 className="mt-2 text-2xl font-bold">
              Separation Questions
            </h3>

            <p className="mt-2 text-sm leading-6 text-[#66736f]">
              Answer Yes or No. Every Yes
              answer activates the relevant
              Inventive Principles.
            </p>

          </div>

          <div className="mt-7 space-y-5">

            {QUESTIONS.map(
              (question, index) => (

                <QuestionCard
                  key={question.id}
                  number={index + 1}
                  question={question}
                  value={
                    answers[question.id]
                  }
                  onChange={(answer) =>
                    setAnswer(
                      question.id,
                      answer
                    )
                  }
                />

              )
            )}

          </div>

        </div>

        {/* RECOMMENDATIONS */}

        <div className="mt-8 rounded-3xl bg-[#123d36] p-7 text-white">

          <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#7ed6bc]">
            Physical Contradiction
          </p>

          <h3 className="mt-2 text-2xl font-bold">
            Recommended Inventive Principles
          </h3>

          <p className="mt-2 max-w-3xl text-sm leading-6 text-white/70">
            Recommendations are generated
            automatically from all separation
            questions answered Yes. Duplicate
            principles are removed.
          </p>

          {recommendedPrinciples.length ===
          0 ? (

            <div className="mt-7 rounded-2xl bg-white/10 p-6">

              <p className="font-semibold">
                No recommendations yet.
              </p>

              <p className="mt-2 text-sm text-white/70">
                Answer Yes to at least one
                separation question to generate
                Inventive Principles.
              </p>

            </div>

          ) : (

            <div className="mt-7 grid gap-5 lg:grid-cols-2">

              {recommendedPrinciples.map(
                (principle) => (

                  <div
                    key={principle.id}
                    className="rounded-2xl bg-white p-6 text-[#123d36]"
                  >

                    <div className="flex items-start gap-4">

                      <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#dff3eb] font-bold">

                        {String(
                          principle.id
                        ).padStart(2, '0')}

                      </div>

                      <div>

                        <h4 className="text-lg font-bold">
                          {principle.name}
                        </h4>

                        <p className="mt-2 text-sm leading-6 text-[#66736f]">
                          {
                            principle.description
                          }
                        </p>

                      </div>

                    </div>

                  </div>

                )
              )}

            </div>

          )}

        </div>

        {/* SOLUTION */}

        <div className="mt-8 rounded-3xl bg-white p-7 shadow-sm">

          <label className="block text-lg font-bold">
            Proposed Solution
          </label>

          <p className="mt-2 text-sm leading-6 text-[#66736f]">
            Optional. Describe the solution
            developed after analysing the Physical
            Contradiction and recommended
            Inventive Principles.
          </p>

          <textarea
            value={proposedSolution}
            onChange={(e) =>
              setProposedSolution(
                e.target.value
              )
            }
            rows={7}
            placeholder="Describe your proposed solution..."
            className="mt-5 w-full resize-none rounded-xl border border-[#cbd5d1] px-4 py-3 outline-none focus:border-[#57b89d]"
          />

        </div>

        {error && (

          <div className="mt-6 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">
            {error}
          </div>

        )}

        {message && (

          <div className="mt-6 rounded-xl bg-green-50 px-4 py-3 text-sm text-green-800">
            {message}
          </div>

        )}

        {/* NAVIGATION */}

        <div className="mt-8 flex flex-col justify-between gap-3 sm:flex-row">

          <button
            onClick={() =>
              router.push(
                `/project/${projectId}/technical-contradiction`
              )
            }
            className="rounded-xl border border-[#123d36] px-7 py-3.5 font-semibold"
          >
            ← Back
          </button>

          <div className="flex flex-col gap-3 sm:flex-row">

            <button
              onClick={() =>
                savePhysicalContradiction(
                  false
                )
              }
              disabled={saving}
              className="rounded-xl border border-[#123d36] px-7 py-3.5 font-semibold disabled:opacity-50"
            >
              {saving
                ? 'Saving...'
                : 'Save'}
            </button>

            <button
              onClick={() =>
                savePhysicalContradiction(
                  true
                )
              }
              disabled={saving}
              className="rounded-xl bg-[#123d36] px-7 py-3.5 font-semibold text-white disabled:opacity-50"
            >
              {saving
                ? 'Saving...'
                : 'Save & Continue →'}
            </button>

          </div>

        </div>

      </section>

    </main>
  );
}

/* =========================================================
   READONLY TECHNICAL CONTRADICTION
   ========================================================= */

function ReadonlyCard({
  title,
  value,
}: {
  title: string;
  value: string;
}) {
  return (
    <div className="rounded-3xl bg-white p-7 shadow-sm">

      <p className="text-sm font-semibold text-[#57b89d]">
        {title}
      </p>

      <p className="mt-3 whitespace-pre-line leading-7">
        {value ||
          'No Technical Contradiction available.'}
      </p>

    </div>
  );
}

/* =========================================================
   PHYSICAL STATES
   ========================================================= */

function StateCard({
  number,
  state,
  setState,
  justification,
  setJustification,
}: {
  number: string;
  state: string;
  setState: (value: string) => void;
  justification: string;
  setJustification: (
    value: string
  ) => void;
}) {
  return (
    <div className="rounded-3xl bg-white p-7 shadow-sm">

      <div className="flex items-center gap-3">

        <div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#dff3eb] font-bold">
          {number}
        </div>

        <h3 className="text-xl font-bold">
          State {number}
        </h3>

      </div>

      <label className="mt-6 block text-sm font-semibold">
        Required State / Property
      </label>

      <textarea
        value={state}
        onChange={(e) =>
          setState(e.target.value)
        }
        rows={4}
        placeholder={
          number === '1'
            ? 'e.g. The object must be hot...'
            : 'e.g. The object must be cold...'
        }
        className="mt-2 w-full resize-none rounded-xl border border-[#cbd5d1] px-4 py-3 outline-none focus:border-[#57b89d]"
      />

      <label className="mt-5 block text-sm font-semibold">
        Why is this state required?
      </label>

      <textarea
        value={justification}
        onChange={(e) =>
          setJustification(
            e.target.value
          )
        }
        rows={4}
        placeholder="Explain why this property or state is necessary..."
        className="mt-2 w-full resize-none rounded-xl border border-[#cbd5d1] px-4 py-3 outline-none focus:border-[#57b89d]"
      />

    </div>
  );
}

/* =========================================================
   SEPARATION QUESTION
   ========================================================= */

function QuestionCard({
  number,
  question,
  value,
  onChange,
}: {
  number: number;
  question: SeparationQuestion;
  value: Answer;
  onChange: (value: Answer) => void;
}) {
  return (
    <div className="rounded-2xl border border-[#d8d5ca] p-5">

      <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">

        <div className="flex gap-4">

          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#dff3eb] text-sm font-bold">
            {number}
          </div>

          <div>

            <p className="font-bold">
              {question.title}
            </p>

            <p className="mt-2 max-w-3xl text-sm leading-6 text-[#66736f]">
              {question.question}
            </p>

          </div>

        </div>

        <div className="flex shrink-0 gap-2">

          {(['Yes', 'No'] as Answer[]).map(
            (answer) => (

              <button
                key={answer}
                type="button"
                onClick={() =>
                  onChange(answer)
                }
                className={`rounded-xl border px-5 py-2.5 text-sm font-semibold transition ${
                  value === answer
                    ? 'border-[#123d36] bg-[#123d36] text-white'
                    : 'border-[#cbd5d1] bg-white hover:bg-[#edf3f1]'
                }`}
              >
                {answer}
              </button>

            )
          )}

        </div>

      </div>

    </div>
  );
}